kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: bank
spec:
  source:
    git:
      ref: master
      uri: 'https://github.com/Trishna-Chakraborty/bank'
    sourceSecret:
      name: github-secret
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: jenkins/JenkinsfileBank
    type: JenkinsPipeline